[patch] add status code log from origin
AthenZ/authorization-proxy pull request #4
Opened 2022-11-21 06:05 UTC by t4niwa

# Description

Print log for status code from origin on `info` level

## Type of change

- [ ] Bug fix
- [x] New feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Non-code changes (update documentation, pipeline, etc.)

### Flags

- [ ] Breaks backward compatibility
- [ ] Requires a documentation update
- [ ] Has untestable code

## Related issue/PR

**Delete this section if there are no issues or pull requests that relate to this pull request.**
- Fixes #_issue_
- Closes #_PR_

---

## Checklist

- [ ] Followed the guidelines in the CONTRIBUTING document
- [ ] Added prefix `[skip ci]`/`[ci skip]`/`[no ci]`/`[skip actions]`/`[actions skip]` in the PR title if necessary
- [ ] Tested and linted the code
- [ ] Commented the code
- [ ] Made corresponding changes to the documentation
- [ ] Passed all pipeline checking

## Checklist for maintainer
- [ ] Use `Squash and merge`
- [ ] Double-confirm the merge message has prefix `[skip ci]`/`[ci skip]`/`[no ci]`/`[skip actions]`/`[actions skip]`
- [ ] Delete the branch after merge

2022-11-28 07:21 UTC, WindzCUHK requested changes

2022-11-28 07:21 UTC, WindzCUHK commented on test/data/example_config.yaml
> +      exclude: [200]
```suggestion
      exclude:
        - 200
```

2022-11-28 07:21 UTC, WindzCUHK commented on handler/handler.go
> +		},
```suggestion
		ModifyResponse: modifyResponse,
```

maybe better to define the function before `&httputil.ReverseProxy{}`?
```go
modifyResponse := func(res *http.Response) error {
    ...
}
if !cfg.OriginLog.StatusCode.Enable {
    modifyResponse = nil
}
```

2022-11-28 08:57 UTC, WindzCUHK commented
@t4niwa 
Can help to add a unit test like below?
https://github.com/AthenZ/authorization-proxy/blob/93fe09aadb4210fd7f8ea1eb9a4427377a69d05c/handler/handler_test.go#L519-L536

Just check when `cfg.OriginLog.StatusCode.Enable == true`, `got.ModifyResponse != nil` is OK.

2022-11-29 04:53 UTC, ssunorz approved these changes

2022-11-29 08:43 UTC, kyfujisa commented
↑の指摘事項への対応が行われたことを確認しました。

2022-11-29 08:44 UTC, kyfujisa approved these changes

2022-11-29 09:17 UTC, WindzCUHK approved these changes

2022-11-30 04:50 UTC, merged